version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - ignaciocardonaobando-code
    assignees:
      - ignaciocardonaobando-code
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps):"
      prefix-development: "chore(deps-dev):"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "package-name"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    reviewers:
      - ignaciocardonaobando-code
